-- MySQL schema for PHP Proposal App
CREATE TABLE IF NOT EXISTS proposals (id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(255) NOT NULL DEFAULT 'IT TRAINING PROGRAM',for_whom VARCHAR(255) DEFAULT '',recipient VARCHAR(255) DEFAULT '',date DATE NOT NULL,intro_text TEXT,signatory_name VARCHAR(255) DEFAULT '',signatory_title VARCHAR(255) DEFAULT '',signatory_phone VARCHAR(64) DEFAULT '',signatory_email VARCHAR(255) DEFAULT '',include_about TINYINT(1) NOT NULL DEFAULT 1,include_technologies TINYINT(1) NOT NULL DEFAULT 1,generated_pdf VARCHAR(255) DEFAULT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS proposal_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  proposal_id INT NOT NULL,
  label VARCHAR(255) NOT NULL,
  type VARCHAR(32) NOT NULL DEFAULT 'content',   -- ⬅ add this
  body TEXT NOT NULL,
  position INT NOT NULL DEFAULT 0,
  FOREIGN KEY (proposal_id) REFERENCES proposals(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
